# PROGRAMACIÓN II: Numpy

### Introducción a NumPy

NumPy es la principal librería de Python para realizar cálculos numéricos eficientes y trabajar con datos estructurados en múltiples dimensiones. Es fundamental para tareas relacionadas con Ciencia de Datos, Machine Learning, y procesamiento de grandes volúmenes de datos, ya que proporciona herramientas optimizadas para manejar arrays y matrices de manera rápida y eficaz.

---

#### **¿Por qué usar NumPy?**

1. **Eficiencia**:
   - Las operaciones sobre arrays en NumPy están optimizadas en C, lo que las hace considerablemente más rápidas que las operaciones equivalentes en listas nativas de Python.

2. **Versatilidad**:
   - Soporta operaciones matemáticas avanzadas, estadísticas, álgebra lineal y generación de números aleatorios.

3. **Compatibilidad**:
   - Es la base de otras librerías populares como Pandas, TensorFlow y scikit-learn.

4. **Facilidad de Uso**:
   - Su sintaxis es simple y permite realizar cálculos complejos con unas pocas líneas de código.

---

#### **Componentes principales de NumPy**

1. **`ndarray`**:
   - La estructura de datos principal de NumPy. Es un contenedor eficiente para datos homogéneos (todos los elementos del mismo tipo).

2. **Módulos especializados**:
   - **`numpy.linalg`**: Álgebra lineal.
   - **`numpy.random`**: Generación de números aleatorios.
   - **`numpy.fft`**: Transformadas de Fourier.
   - **`numpy.matlib`**: Operaciones con matrices.

3. **Operaciones Vectorizadas**:
   - Permite realizar cálculos sobre arrays completos sin necesidad de bucles explícitos, lo que mejora la claridad y el rendimiento del código.

---

#### **¿Qué aprenderás con NumPy?**

En esta guía, exploraremos los fundamentos de NumPy, incluyendo:
- Creación y manipulación de arrays.
- Operaciones matemáticas, estadísticas y de álgebra lineal.
- Técnicas avanzadas como la indexación y transformación de datos.
- Generación de datos aleatorios para simulaciones y análisis.

NumPy es la base de muchas aplicaciones de análisis de datos y aprendizaje automático, por lo que dominar esta librería es esencial para cualquier profesional en este campo.

In [2]:
import numpy as np

## NumPy Arrays

El **array** es la estructura de datos fundamental en NumPy. Es un contenedor eficiente diseñado para almacenar y operar con datos homogéneos (todos los elementos deben ser del mismo tipo) en múltiples dimensiones.

---

### **Características Principales de los Arrays en NumPy**

1. **Homogeneidad**:
   - Todos los elementos de un array deben ser del mismo tipo (entero, flotante, booleano, etc.).
   - Esto permite optimizar operaciones matemáticas y de memoria.

2. **Multidimensionalidad**:
   - Soporte para arrays de una dimensión (**vectores**), dos dimensiones (**matrices**), o más dimensiones.

3. **Eficiencia**:
   - Los arrays de NumPy están implementados en C, lo que los hace significativamente más rápidos que las listas nativas de Python para operaciones matemáticas y manipulación de datos.

4. **Soporte para Operaciones Vectorizadas**:
   - Permite realizar cálculos matemáticos en todo el array sin necesidad de bucles explícitos.

---

### **Tipos de Arrays en NumPy**

1. **Array 1D (Vector)**:
   - Es un array de una sola dimensión.
   - Ejemplo:


In [3]:
vector = np.array([1, 2, 3])
print("Vector:", vector)


Vector: [1 2 3]


2. **Array 2D (Matriz)**:
   - Es un array con dos dimensiones (filas y columnas).
   - Ejemplo:


In [5]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz:")
print(matriz)

Matriz:
[[1 2 3]
 [4 5 6]]


3. **Array ND (Multidimensional)**:
   - Arrays con más de dos dimensiones, útiles para imágenes, datos volumétricos, etc.
   - Ejemplo:


In [4]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Array 3D:")
print(array_3d)

Array 3D:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### **Argumentos de los Arrays en NumPy**

Cuando creamos un array en NumPy utilizando la función `np.array()`, podemos personalizar su comportamiento mediante los argumentos que acepta esta función. Estos argumentos nos permiten especificar detalles como el tipo de datos, la copia de memoria, el orden de los datos, entre otros.

---

#### Sintaxis General de `np.array()`

In [ ]:
np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

A continuación, desglosamos cada argumento con ejemplos prácticos.

---

#### **1. `object` (Obligatorio)**

El objeto de entrada que será convertido en un array. Puede ser una lista, tupla, array existente u otros objetos similares.

**Ejemplo:**


In [6]:
# El parámetro object puede ser una lista, una tupla, un array de numpy, etc.
lista = [1, 2, 3]
array = np.array(lista) # Pasamos la lista a un array de numpy
print(array)  # Salida: [1 2 3]


[1 2 3]



---

#### **2. `dtype` (Opcional)**

Especifica el tipo de datos del array resultante. Si no se indica, NumPy lo infiere automáticamente.

**Ejemplo:**


In [8]:
# Especificamos el tipo de dato de los elementos del array
array = np.array([1.2, 2.3, 3.5], dtype=float) # Array de floats
print(array)  # Salida: [1. 2. 3.]

[1.2 2.3 3.5]



**Notas:**
- Tipos comunes: `int`, `float`, `bool`, `complex`, entre otros.
- Puede ser útil para optimizar memoria o precisión en cálculos.

---

#### **3. `copy` (Opcional, por defecto `True`)**

Indica si el array debe ser una copia del objeto de entrada o si puede compartir memoria con el original.

**Ejemplo:**




In [9]:
original = np.array([1, 2, 3])

# Nos permite copiar el array original y modificar la copia sin modificar el original y ahorrar memoria
copia = np.array(original, copy=False) # El argumento object en este caso es un array de numpy
print(original is copia)  # Salida: True (comparten memoria)

True


**Notas:**
- Si el objeto ya es un array (`ndarray`) y `copy=False`, se evita hacer una copia redundante.

---

#### **4. `order` (Opcional, por defecto `'K'`)**

Define cómo se almacenan los datos en memoria:
- `'C'`: Orden por filas (estilo C).
- `'F'`: Orden por columnas (estilo Fortran).
- `'A'`: Hereda el orden del objeto original.
- `'K'`: Mantiene el orden del objeto siempre que sea posible.

**Ejemplo:**


In [11]:
import numpy as np

# Array inicial con orden C
array = np.array([[1, 2], [3, 4]], order='C')  # Almacenado en orden C
print("Orden C:")
print(array)
print("Es C_CONTIGUOUS:", array.flags['C_CONTIGUOUS'])  # True
print("Es F_CONTIGUOUS:", array.flags['F_CONTIGUOUS'])  # False
print()

# Array convertido a orden Fortran
array2 = np.array(array, order='F')  # Convertimos a orden Fortran
print("Orden Fortran:")
print(array2)
print("Es C_CONTIGUOUS:", array2.flags['C_CONTIGUOUS'])  # False
print("Es F_CONTIGUOUS:", array2.flags['F_CONTIGUOUS'])  # True
print()

# Array convertido con orden A (hereda del objeto original)
array3 = np.array(array, order='A')  # Hereda el orden del array original
print("Orden A (heredado):")
print(array3)
print("Es C_CONTIGUOUS:", array3.flags['C_CONTIGUOUS'])  # True (igual que el original)
print("Es F_CONTIGUOUS:", array3.flags['F_CONTIGUOUS'])  # False (igual que el original)
print()

# Array convertido con orden K (más eficiente)
array4 = np.array(array, order='K')  # Elige el orden más eficiente
print("Orden K (más eficiente):")
print(array4)
print("Es C_CONTIGUOUS:", array4.flags['C_CONTIGUOUS'])  # True (en este caso)
print("Es F_CONTIGUOUS:", array4.flags['F_CONTIGUOUS'])  # False


Orden C:
[[1 2]
 [3 4]]
Es C_CONTIGUOUS: True
Es F_CONTIGUOUS: False

Orden Fortran:
[[1 2]
 [3 4]]
Es C_CONTIGUOUS: False
Es F_CONTIGUOUS: True

Orden A (heredado):
[[1 2]
 [3 4]]
Es C_CONTIGUOUS: True
Es F_CONTIGUOUS: False

Orden K (más eficiente):
[[1 2]
 [3 4]]
Es C_CONTIGUOUS: True
Es F_CONTIGUOUS: False


### Explicación:

1. **Orden C**:
   - Los datos están almacenados por filas (C-style).

2. **Orden Fortran**:
   - Los datos están almacenados por columnas (Fortran-style).

3. **Orden A**:
   - Hereda el orden del array original. Aquí coincide con el orden C.

4. **Orden K**:
   - Usa el orden más eficiente posible basado en el almacenamiento existente. Aquí también coincide con C debido al objeto original.


#### **5. `subok` (Opcional, por defecto `False`)**

Permite que las subclases de `ndarray` se conserven. Si es `False`, siempre devuelve un `ndarray` estándar.

El argumento **`subok`** en la función `np.array()` controla si las **subclases de `ndarray`** se conservan al convertir un objeto a un array. Esto es importante en casos donde el objeto de entrada es una subclase personalizada de `ndarray` (por ejemplo, `numpy.matrix`).

---

### ¿Qué es una subclase de `ndarray`?

En NumPy, el objeto básico para trabajar con datos es el `ndarray`. Sin embargo, hay subclases que heredan de `ndarray` y añaden funcionalidad específica. Por ejemplo:
- **`numpy.matrix`**: Es una subclase de `ndarray` diseñada para cálculos matriciales, que siempre retorna matrices 2D.

---

### ¿Qué hace el argumento `subok`?

1. **`subok=True`**:
   - Si el objeto de entrada es una subclase de `ndarray`, NumPy devuelve un objeto de la misma subclase en lugar de un `ndarray` estándar.
   - Es decir, **se conserva el tipo del objeto de entrada**.

2. **`subok=False` (comportamiento por defecto)**:
   - Ignora si el objeto de entrada es una subclase y siempre devuelve un `ndarray` estándar.

### ¿Por qué es útil?

El argumento `subok` permite controlar si se respeta la naturaleza del objeto de entrada o si se fuerza a un `ndarray` estándar. Esto es importante en escenarios donde las subclases tienen un comportamiento especial que necesitas conservar.


**Ejemplo:**


In [12]:
from numpy import matrix
matriz = matrix([[1, 2], [3, 4]])
array = np.array(matriz, subok=True)
print(type(array))  # Salida: <class 'numpy.matrix'>

<class 'numpy.matrix'>


#### **6. `ndmin` (Opcional, por defecto `0`)**

Establece el número mínimo de dimensiones del array. Si el objeto tiene menos dimensiones, se añaden dimensiones adicionales.

**Ejemplo:**



In [19]:
array = np.array([1, 2, 3])
print(array.shape)  # Salida: (3,) (Array unidimensional)

array2 = np.array(array, ndmin=2)
print(array2.shape)  # Salida: (1, 3) (Array bidimensional)

array3 = np.array(array, ndmin=3)
print(array3.shape)  # Salida: (1, 1, 3) (Array tridimensional)

array4 = np.array(array, ndmin=4)
print(array4.shape)  # Salida: (1, 1, 1, 3) (Array de 4 dimensiones)

(3,)
(1, 3)
(1, 1, 3)
(1, 1, 1, 3)


### Resumen de Argumentos

| Argumento  | Descripción                                                 | Valor por Defecto |
|------------|-------------------------------------------------------------|-------------------|
| `object`   | Objeto que se convertirá en un array.                       | Obligatorio       |
| `dtype`    | Especifica el tipo de datos del array.                      | `None`            |
| `copy`     | Indica si se debe crear una copia del objeto de entrada.    | `True`            |
| `order`    | Orden en memoria: `'C'`, `'F'`, `'A'` o `'K'`.             | `'K'`             |
| `subok`    | Permite subclases de `ndarray` si es `True`.                | `False`           |
| `ndmin`    | Número mínimo de dimensiones del array.                     | `0`               |

### Ejemplo Combinado


In [20]:
import numpy as np

lista = [1, 2, 3]
array = np.array(lista, dtype=float, copy=True, order='C', ndmin=2)

print("Array:")
print(array)
print("Dimensiones:", array.ndim)  # 2
print("Forma:", array.shape)       # (1, 3)
print("Tipo de dato:", array.dtype)  # float64

Array:
[[1. 2. 3.]]
Dimensiones: 2
Forma: (1, 3)
Tipo de dato: float64


### **Propiedades de los Arrays**
---

A diferencia de los **argumentos** que se utilizan al crear un array con **`np.array`**, las **propiedades** permiten analizar y manipular arrays ya creados. Estas propiedades son útiles para explorar características generales del array, como su forma, tamaño o tipo de datos, sin necesidad de modificar directamente su contenido o estructura. Esto es especialmente práctico cuando trabajamos con conjuntos de datos importados, ya que nos permite obtener una visión general y realizar transformaciones a nivel global sin editar cada fila o columna individualmente.

---


NumPy ofrece métodos para inspeccionar y manipular arrays:


## **Tenemos:**

1. **`ndim`**:
   - Muestra el número de dimensiones del array.
   - **Ejemplo**:


In [21]:
import numpy as np
array = np.array([[1, 2], [3, 4]])
print(array.ndim)

2


Es útil para:

1. **Inspección de datos**:
   - Determinar si los datos son unidimensionales (vectores), bidimensionales (matrices) o tienen más dimensiones (arrays ND).

2. **Validación**:
   - Comprobar si los datos tienen las dimensiones esperadas antes de realizar operaciones específicas.

3. **Optimización de código**:
   - Ajustar procesos o algoritmos en función de la dimensionalidad del array.

4. **Preparación de datos**:
   - Identificar cuándo es necesario modificar las dimensiones del array utilizando métodos como `reshape` o `expand_dims`.

5. **Análisis estructural**:
   - Comprender la organización interna de los datos, especialmente en casos de análisis multidimensional, como imágenes o datos volumétricos.

Este atributo es clave para garantizar que las operaciones sobre arrays sean aplicadas correctamente según su dimensionalidad. 

---

2. **`shape`**:
   - Devuelve una tupla que describe el número de elementos en cada dimensión.
   - **Ejemplo**:



In [22]:
array = np.array([[1, 2], [3, 4]])
print(array.shape) 

(2, 2)


Es útil para:

1. **Inspección de la estructura de datos**:
   - Verificar cómo están organizados los elementos en el array, como filas y columnas en matrices o dimensiones en arrays ND.

2. **Validación**:
   - Comprobar si la forma del array coincide con los requisitos de un modelo o algoritmo antes de realizar operaciones.

3. **Transformaciones**:
   - Utilizar la información de la forma para reorganizar los datos con métodos como `reshape` o para adaptar arrays a formas compatibles.

4. **Indexación avanzada**:
   - Facilitar operaciones basadas en dimensiones específicas del array.

5. **Análisis estructural**:
   - Entender la composición de datos multidimensionales en áreas como procesamiento de imágenes, análisis científico o aprendizaje automático.

El atributo `shape` es esencial para comprender y manipular la disposición de los datos en arrays. 

---

3. **`size`**:
   - Número total de elementos en el array.
   - **Ejemplo**:

In [ ]:
array = np.array([[1, 2], [3, 4]])
print(array.size)  # Salida: 4

Es útil para:

1. **Inspección de datos**:
   - Saber cuántos elementos contiene el array, independientemente de su dimensionalidad o forma.

2. **Validación**:
   - Comprobar si la cantidad de datos en el array coincide con las expectativas o requisitos de una operación o modelo.

3. **Cálculos de memoria**:
   - Determinar el espacio que ocupa un array en memoria junto con `itemsize` o `nbytes`.

4. **Preparación de datos**:
   - Confirmar que el número total de elementos permite realizar transformaciones, como `reshape`, sin perder datos.

5. **Optimización**:
   - Ajustar procesos que dependen de la cantidad total de datos, como divisiones en lotes o particionamiento.

El atributo `size` es clave para entender el volumen total de datos almacenados en un array y planificar operaciones en consecuencia.

---

4. **`dtype`**:
   - Muestra el tipo de datos de los elementos del array.
   - **Ejemplo**:

In [ ]:
array = np.array([1, 2, 3], dtype=float)
print(array.dtype)  # Salida: float64

Esto es útil para:

1. **Inspección de datos**:
   - Verificar qué tipo de datos (por ejemplo, `int`, `float`, `bool`, `complex`, etc.) están almacenados en el array.

2. **Optimización de memoria**:
   - Permite elegir tipos de datos más compactos (como `int8` o `float32`) para ahorrar espacio en memoria, especialmente al trabajar con grandes volúmenes de datos.

3. **Precisión en cálculos**:
   - Garantiza que los cálculos numéricos se realicen con la precisión deseada, seleccionando tipos como `float64` o `complex128`.

4. **Compatibilidad**:
   - Facilita la interoperabilidad con otras bibliotecas o sistemas que requieren un tipo de datos específico.

5. **Transformaciones de tipos**:
   - Usar la propiedad `dtype` junto con funciones como `astype` permite convertir los datos a otro tipo cuando sea necesario.

El atributo `dtype` es fundamental para comprender cómo están representados los datos dentro de un array y planificar operaciones de manera eficiente. 

---

5. **`itemsize`**:
   - Tamaño (en bytes) de cada elemento del array.
   - **Ejemplo**:


In [ ]:
array = np.array([1, 2, 3], dtype=np.int32)
print(array.itemsize)  # Salida: 4 (int32 usa 4 bytes)

Esto es útil para:

1. **Cálculo de memoria**:
   - Determinar cuánto espacio ocupa cada elemento del array en memoria. Esto es especialmente importante al trabajar con grandes volúmenes de datos.

2. **Optimización de recursos**:
   - Ayuda a decidir el tipo de datos más eficiente (`int8`, `float32`, etc.) para reducir el uso de memoria, manteniendo un balance entre precisión y almacenamiento.

3. **Análisis de tipos de datos**:
   - Verificar si el tipo de datos seleccionado es adecuado para el rango de valores que se van a manejar.

4. **Compatibilidad con hardware**:
   - Asegurarse de que los datos tengan el tamaño adecuado para operaciones específicas, como cálculos en GPUs o dispositivos de bajo rendimiento.

El tamaño en bytes de cada tipo de datos depende directamente del tipo (`dtype`) del array. Por ejemplo:
- `int32` utiliza 4 bytes (32 bits).
- `float64` utiliza 8 bytes (64 bits).

El atributo `itemsize` es esencial para evaluar el impacto en memoria y garantizar un uso eficiente de los recursos.

---


6. **`nbytes`**:
   - Tamaño total del array en memoria (en bytes).
   - Calculado como `size * itemsize`.
   - **Ejemplo**:


In [ ]:
array = np.array([1, 2, 3], dtype=np.int32)
print(array.nbytes)  # Salida: 12 (3 elementos * 4 bytes cada uno)

Esto es útil para:

1. **Estimación del uso de memoria total**:
   - Determinar cuánto espacio ocupa todo el array en memoria, basado en el tamaño de sus elementos (`itemsize`) y el número total de elementos (`size`).

2. **Optimización de memoria en grandes arrays**:
   - Identificar arrays que ocupan mucho espacio y considerar la posibilidad de reducir el tipo de datos (`dtype`) para ahorrar memoria.

3. **Cálculo de recursos para almacenamiento o transferencia**:
   - Ayuda a prever los recursos necesarios para almacenar o transferir datos, especialmente en redes, sistemas distribuidos o almacenamiento externo.

4. **Depuración de problemas de memoria**:
   - Verificar si el uso total de memoria de un array es adecuado para el hardware disponible, especialmente en sistemas con limitaciones de RAM.

El tamaño total en bytes es calculado como:
```
nbytes = size * itemsize
```
Por ejemplo:
- Un array con 3 elementos de tipo `int32` (4 bytes por elemento) ocupa `3 * 4 = 12 bytes`.

El atributo `nbytes` es crucial para optimizar aplicaciones que trabajan con grandes volúmenes de datos o sistemas con recursos limitados.

---


7. **`T`** (Transpuesta):
   - Devuelve la transpuesta del array (intercambia filas y columnas en un array 2D).
   - **Ejemplo**:

In [ ]:
array = np.array([[1, 2], [3, 4]])
print(array.T)

Esto es útil para:

1. **Intercambiar filas y columnas**:
   - Cambiar la orientación de los datos en un array bidimensional (matriz), convirtiendo filas en columnas y viceversa.

2. **Procesamiento de datos matriciales**:
   - Facilitar operaciones que dependen de la disposición de los datos, como productos matriciales o análisis en álgebra lineal.

3. **Compatibilidad con funciones matemáticas**:
   - Alinear los datos según la estructura requerida para funciones específicas, especialmente en bibliotecas como NumPy o SciPy.

4. **Preparación de datos**:
   - Ajustar la forma de los datos para su visualización o análisis, asegurando que estén en la disposición deseada.

**Nota**:
- El atributo `.T` no crea una copia de los datos, sino que devuelve una vista transpuesta del array original. Esto hace que sea eficiente en términos de memoria.

---


8. **`flat`**:
   - Iterador que permite recorrer los elementos del array como si fuera 1D.
   - **Ejemplo**:


In [ ]:
array = np.array([[1, 2], [3, 4]])
for elem in array.flat:
    print(elem)

Esto es útil para:

1. **Iterar sobre todos los elementos de un array multidimensional**:
   - Permite recorrer los elementos de un array como si fueran unidimensionales, sin importar su estructura original.

2. **Acceso secuencial a los datos**:
   - Facilita el acceso a cada elemento en orden, útil para operaciones que procesan datos elemento por elemento.

3. **Procesamiento eficiente de datos**:
   - Proporciona una forma directa de iterar sin necesidad de anidar bucles para recorrer filas y columnas.

4. **Compatibilidad con algoritmos**:
   - Asegura que los datos se puedan procesar en secuencia, lo que puede ser útil en algoritmos que requieren acceso secuencial.

**Nota**:
- El atributo `.flat` devuelve un **iterador** que recorre todos los elementos del array en orden de almacenamiento (C o Fortran, según corresponda).
- No crea una copia del array, por lo que es eficiente en términos de memoria.

---


9. **`base`**:
    - Muestra si el array comparte memoria con otro objeto.
    - **Ejemplo**:


In [ ]:
original = np.array([1, 2, 3])
view = original[1:]  # Crea una vista del array
print(view.base is original)  

Esto es útil para:

1. **Verificar si un array es una vista de otro**:
   - Permite comprobar si un array comparte datos con otro array original, en lugar de ser una copia independiente.

2. **Optimización de memoria**:
   - Identificar cuándo los datos se comparten entre arrays, lo que evita duplicación innecesaria en memoria.

3. **Depuración y validación**:
   - Garantiza que las operaciones realizadas en vistas no alteren el array original de forma inesperada, o viceversa.

4. **Análisis de estructura y relaciones**:
   - Facilita entender cómo se relacionan los arrays derivados de un array base, especialmente en aplicaciones donde se crean múltiples vistas para diferentes operaciones.

**Nota**:
- El atributo `.base` apunta al array original del cual se derivó la vista.
- Si un array no es una vista, su atributo `.base` será `None`.

---


10. **`strides`**:
    - Describe cómo avanzar en memoria para moverse de un elemento a otro en cada dimensión.
    - **Ejemplo**:


In [ ]:
array = np.array([[1, 2], [3, 4]])
print(array.strides)  # Salida: (8, 4) (en bytes, depende del tipo de datos)

Esto es útil para:

1. **Comprender el almacenamiento en memoria**:
   - El atributo **`strides`** indica el número de bytes necesarios para moverse entre elementos a lo largo de cada dimensión del array. Esto refleja cómo se organizan los datos en memoria.

2. **Optimización del acceso a datos**:
   - Ayuda a analizar y optimizar el rendimiento de operaciones que implican acceso secuencial a los elementos del array.

3. **Depuración de transformaciones**:
   - Facilita la identificación de problemas al trabajar con operaciones como `reshape` o al crear vistas que cambian la forma del array.

4. **Compatibilidad con órdenes de memoria**:
   - Verifica si los datos se almacenan en orden C (por filas) o Fortran (por columnas), lo cual es importante en aplicaciones que dependen de un almacenamiento específico.

**Nota**:
- El valor de `strides` depende del tipo de datos (`dtype`) y del orden de almacenamiento en memoria:
  - Para un array de `int32` (4 bytes por elemento) con forma `(2, 2)`:
    - `strides = (8, 4)` significa que:
      - Moverse entre filas requiere 8 bytes (2 elementos por fila × 4 bytes).
      - Moverse entre columnas requiere 4 bytes (1 elemento por columna × 4 bytes).


---


11. **`reshape`**:
    - Cambia la forma del array sin modificar su contenido.
    - **Ejemplo**:


In [ ]:
array = np.array([1, 2, 3, 4])
reshaped = array.reshape((2, 2))
print(reshaped)

Esto es útil para:

1. **Reorganizar la estructura de datos**:
   - El método **`reshape`** permite cambiar la forma de un array sin alterar sus datos, reorganizándolos en nuevas dimensiones.

2. **Preparar datos para modelos o algoritmos**:
   - Es esencial para ajustar la forma de los datos según los requisitos de modelos de machine learning, redes neuronales o algoritmos de procesamiento de datos.

3. **Manipulación multidimensional**:
   - Facilita transformar arrays unidimensionales en matrices o arrays con más dimensiones para su análisis o visualización.

4. **Validación de compatibilidad**:
   - Garantiza que la nueva forma sea compatible con el número total de elementos del array original. Si no lo es, se lanza un error.

**Nota**:
- El método `reshape` no crea una copia de los datos si no es necesario; en su lugar, devuelve una vista del array original, siempre que sea posible.



---

12.  **`split`**:
   - Divide un array en múltiples sub-arrays según un número específico de divisiones.
   - **Ejemplo**:

In [29]:
array = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.split(array, 3)
print(sub_arrays)

[array([1, 2]), array([3, 4]), array([5, 6])]


Esto es útil para:

1. **División de datos en partes más pequeñas**:
   - Permite segmentar arrays grandes en sub-arrays más manejables para análisis o procesamiento por lotes.

2. **Preparación de datos para paralelización**:
   - Facilita la distribución de datos entre múltiples procesos o threads, optimizando el rendimiento en tareas de computación intensiva.

3. **Manipulación de datos secuenciales**:
   - Divide datos unidimensionales en fragmentos para operaciones independientes, como análisis de series temporales.

4. **Validación de partición uniforme**:
   - Garantiza que el número total de elementos en el array original sea divisible por el número de particiones. Si no lo es, genera un error.

**Nota**:
- Si necesitas dividir un array en secciones desiguales, puedes usar **`np.array_split`** en lugar de `np.split`.




---

### Resumen

| Propiedad     | Descripción                                    | Ejemplo de Salida      |
|---------------|------------------------------------------------|------------------------|
| `ndim`        | Número de dimensiones del array.               | `2`                   |
| `shape`       | Forma del array (elementos por dimensión).     | `(2, 2)`              |
| `size`        | Número total de elementos.                     | `4`                   |
| `dtype`       | Tipo de datos de los elementos.                | `float64`             |
| `itemsize`    | Tamaño en bytes de cada elemento.              | `4`                   |
| `nbytes`      | Tamaño total en memoria en bytes.              | `12`                  |
| `T`           | Transpuesta del array.                         | `[[1 3], [2 4]]`      |
| `flat`        | Iterador sobre elementos del array.            | `[1, 2, 3, 4]`        |
| `real`        | Parte real de los elementos complejos.         | `[1., 3.]`            |
| `imag`        | Parte imaginaria de los elementos complejos.   | `[2., 4.]`            |
| `base`        | Indica si comparte memoria con otro objeto.    | `True`                |
| `strides`     | Desplazamiento en bytes entre elementos.       | `(8, 4)`              |
| `split`       | Divide el conjutno de datos                    |                       |

### **Beneficios del Uso de Arrays**
---

1. **Eficiencia en memoria y cálculo**:
   - A diferencia de las listas de Python, los arrays son más compactos y rápidos.

2. **Operaciones matemáticas simplificadas**:
   - Las operaciones se aplican elemento por elemento automáticamente.
   - Ejemplo:

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # [5, 7, 9]

3. **Soporte para datos multidimensionales**:
   - Ideal para análisis de datos, computación científica y aprendizaje automático.

# **Ordenación de Arrays en NumPy**

NumPy ofrece herramientas potentes para ordenar arrays de manera eficiente. Estas funciones permiten organizar los datos en orden ascendente o descendente, e incluso obtener los índices de ordenación.

La ordenación es útil en muchas tareas, como:
- Clasificación de datos.
- Preparación de datos para análisis.
- Encontrar valores extremos (mínimos/máximos) en contextos específicos.

---

## **1. Ordenar un Array con `np.sort`**

La función `np.sort` devuelve una copia del array original, pero ordenada.

### **Sintaxis:**
`np.sort(array, axis=-1, kind='quicksort', order=None)`

- `array`: El array que deseas ordenar.
- `axis`: El eje a ordenar (por defecto es el último eje, `-1`).
- `kind`: Algoritmo de ordenación. Por defecto es `quicksort`, pero también puedes usar `mergesort` o `heapsort`.
- `order`: Ordenar por un campo específico en arrays estructurados.

---

### **Ejemplo: Ordenación Básica**


In [ ]:
import numpy as np

# Crear un array unidimensional
array = np.array([3, 1, 4, 1, 5, 9, 2])

# Ordenar el array en orden ascendente
array_ordenado = np.sort(array)

# Imprimimos resultados
print("Array original:", array)
print("Array ordenado:", array_ordenado)

## **2. Obtener Índices de Ordenación con `np.argsort`**

La función `np.argsort` devuelve los índices que ordenarían un array. Esto es útil para reordenar otros arrays basados en el orden de un array dado.

### **Sintaxis:**
`np.argsort(array, axis=-1, kind='quicksort', order=None)`

---

### **Ejemplo: Índices de Ordenación**


In [ ]:
# Obtener los índices de ordenación
indices_orden = np.argsort(array)

# Usar los índices para reordenar el array
array_reordenado = array[indices_orden]

# Imprimimos resultados
print("Índices de ordenación:", indices_orden)
print("Array reordenado usando índices:", array_reordenado)

## **3. Ordenación en Arrays Multidimensionales**

En arrays multidimensionales, puedes especificar el eje (`axis`) sobre el cual realizar la ordenación.

---

### **Ejemplo: Ordenar por Filas y Columnas**


In [ ]:
# Crear un array bidimensional
matriz = np.array([[5, 3, 8], [2, 7, 1], [6, 4, 9]])

# Ordenar por filas (eje 1)
ordenado_por_filas = np.sort(matriz, axis=1)

# Ordenar por columnas (eje 0)
ordenado_por_columnas = np.sort(matriz, axis=0)

# Imprimimos resultados
print("Matriz original:\n", matriz)
print("Matriz ordenada por filas:\n", ordenado_por_filas)
print("Matriz ordenada por columnas:\n", ordenado_por_columnas)

## **4. Métodos Avanzados de Ordenación**

### **`np.partition`**
Divide un array en dos partes: los valores menores a un pivote y los mayores o iguales.

### **`np.lexsort`**
Ordena de acuerdo con varias claves.

---

### **Ejemplo: Ordenación con `np.partition`**


In [ ]:
# Usar np.partition para dividir por el tercer elemento (índice 2)
partitioned = np.partition(array, 2)

# Imprimimos resultados
print("Array particionado por el índice 2:", partitioned)

### **Tabla Resumen de Métodos de Ordenación**

| **Método**       | **Propósito**                                          | **Ejemplo**                      |
|-------------------|-------------------------------------------------------|-----------------------------------|
| `np.sort`         | Ordena un array.                                      | `np.sort(array)`                 |
| `np.argsort`      | Devuelve los índices para ordenar el array.           | `np.argsort(array)`              |
| `np.partition`    | Divide el array según un pivote.                      | `np.partition(array, 2)`         |
| `np.lexsort`      | Ordena según varias claves.                           | `np.lexsort((key1, key2))`       |

---

### **Conclusión**

Las herramientas de ordenación en NumPy son fundamentales para organizar y clasificar datos en análisis y aplicaciones numéricas. Dependiendo de la tarea, puedes elegir entre ordenar valores directamente, obtener índices de ordenación o usar métodos avanzados para dividir y clasificar datos más complejos.

---

## **Combinación de Arrays en NumPy**

La combinación de arrays en NumPy es una herramienta esencial para trabajar con datos de diferentes fuentes o para reorganizarlos en nuevas estructuras. NumPy ofrece varias funciones para combinar arrays, que se dividen principalmente en concatenación horizontal y concatenación vertical.

---

### 1. **Concatenación con `np.concatenate`**

**Descripción**:
- Combina dos o más arrays a lo largo de un eje especificado.

**Argumentos principales**:
- `arrays`: Lista de arrays que se desean combinar.
- `axis`: Eje a lo largo del cual se realiza la combinación (por defecto, `axis=0`).


In [37]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])

# Concatenación vertical (por filas)
resultado1 = np.concatenate((array1, array2), axis=0)
print("Concatenación vertical:")
print(resultado1)

# Concatenación horizontal (por columnas)
array3 = np.array([[5], [6]])
resultado2 = np.concatenate((array1, array3), axis=1)
print("\nConcatenación horizontal:")
print(resultado2)


Concatenación vertical:
[[1 2]
 [3 4]
 [5 6]]

Concatenación horizontal:
[[1 2 5]
 [3 4 6]]


### **2. Apilado Vertical con `np.vstack`**

**Descripción**:
- Combina arrays apilándolos verticalmente (como filas).
- Es equivalente a `np.concatenate` con `axis=0`.


In [38]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])

resultado = np.vstack((array1, array2))
print("Apilado vertical:")
print(resultado)

Apilado vertical:
[[1 2]
 [3 4]]


### **3. Apilado Horizontal con `np.hstack`**

**Descripción**:
- Combina arrays apilándolos horizontalmente (como columnas).
- Es equivalente a `np.concatenate` con `axis=1`.


In [39]:
array1 = np.array([1, 2]).reshape(2, 1)
array2 = np.array([3, 4]).reshape(2, 1)

resultado = np.hstack((array1, array2))
print("Apilado horizontal:")
print(resultado)


Apilado horizontal:
[[1 3]
 [2 4]]


### **4. División en Profundidad con `np.dstack`**

**Descripción**:
- Apila arrays a lo largo de un tercer eje (profundidad).
- Crea un array tridimensional.


In [40]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

resultado = np.dstack((array1, array2))
print("Apilado en profundidad:")
print(resultado)


Apilado en profundidad:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


### **5. Apilado por Ejes con `np.stack`**

**Descripción**:
- Combina arrays a lo largo de un nuevo eje.
- Es más general que `vstack` y `hstack`.


In [41]:
array1 = np.array([1, 2])
array2 = np.array([3, 4])

# Eje nuevo en filas
resultado = np.stack((array1, array2), axis=0)
print("Apilado con nuevo eje (filas):")
print(resultado)

# Eje nuevo en columnas
resultado2 = np.stack((array1, array2), axis=1)
print("\nApilado con nuevo eje (columnas):")
print(resultado2)


Apilado con nuevo eje (filas):
[[1 2]
 [3 4]]

Apilado con nuevo eje (columnas):
[[1 3]
 [2 4]]


### **Resumen de Funciones**

| Método           | Descripción                                      | Eje por Defecto |
|-------------------|--------------------------------------------------|-----------------|
| `np.concatenate` | Combina arrays a lo largo de un eje especificado. | `axis=0`        |
| `np.vstack`      | Apila arrays verticalmente (como filas).          | `axis=0`        |
| `np.hstack`      | Apila arrays horizontalmente (como columnas).     | `axis=1`        |
| `np.dstack`      | Apila arrays a lo largo del eje de profundidad.   | Nuevo eje (3D)  |
| `np.stack`       | Apila arrays a lo largo de un nuevo eje.          | Configurable    |


## **Métodos de Inicialización de Arrays en NumPy**

NumPy ofrece varias funciones para inicializar arrays con valores predefinidos. Estos métodos son útiles para crear estructuras base para cálculos y simulaciones.

---

#### **1. Zeros (`np.zeros`)**
- Crea un array lleno de ceros.
- **Argumentos principales**:
  - `shape`: Dimensiones del array (tupla o entero).
  - `dtype` (opcional): Tipo de datos de los elementos.

**Ejemplo:**



In [ ]:
import numpy as np
np.zeros(3)  # Array 1D de ceros
np.zeros((5, 5))  # Matriz 5x5 de ceros

---

#### **2. Ones (`np.ones`)**
- Crea un array lleno de unos.
- **Argumentos principales**:
  - `shape`: Dimensiones del array (tupla o entero).
  - `dtype` (opcional): Tipo de datos de los elementos.

**Ejemplo:**



In [ ]:
np.ones(3)  # Array 1D de unos
np.ones((2, 3))  # Matriz 2x3 de unos


---

#### **3. Arange (`np.arange`)**
- Genera un array con valores dentro de un rango específico.
- Similar a `range` en Python, pero devuelve un array.
- **Argumentos principales**:
  - `start`: Valor inicial (incluido).
  - `stop`: Valor final (excluido).
  - `step` (opcional): Incremento entre valores.

**Ejemplo:**



In [28]:
np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]

array([0, 2, 4, 6, 8])


---

#### **4. Linspace (`np.linspace`)**
- Genera un array de valores igualmente espaciados dentro de un rango.
- **Argumentos principales**:
  - `start`: Valor inicial.
  - `stop`: Valor final.
  - `num`: Número de valores generados.

**Ejemplo:**


In [27]:
np.linspace(0, 1, 5)  # [0. , 0.25, 0.5 , 0.75, 1. ]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

---

#### **5. Random (`np.random`)**
NumPy ofrece funciones para inicializar arrays con valores aleatorios:

- **Aleatorios uniformes** (`np.random.rand`):
  - Genera valores en el rango `[0, 1)`.


In [26]:
np.random.rand(3, 2)  # Matriz 3x2 con valores aleatorios

array([[0.54064649, 0.16153197],
       [0.96221222, 0.97631096],
       [0.57920709, 0.26963502]])

- **Aleatorios con distribución normal** (`np.random.randn`):
  - Genera valores con distribución normal estándar.


In [25]:
np.random.randn(3, 2)  # Matriz 3x2 con valores normales

array([[-0.84995761, -0.2575042 ],
       [-0.5516221 , -1.29954047],
       [ 3.05568598, -0.3153326 ]])


- **Valores enteros aleatorios** (`np.random.randint`):
  - Genera enteros aleatorios dentro de un rango.


In [24]:
np.random.randint(0, 10, (3, 3))  # Matriz 3x3 con enteros entre 0 y 9

array([[7, 6, 7],
       [0, 5, 2],
       [9, 7, 1]])


---

#### **6. Eye (`np.eye`)**
- Crea una matriz identidad (matriz diagonal con unos en la diagonal principal).
- **Argumentos principales**:
  - `N`: Tamaño de la matriz (NxN).
  - `k` (opcional): Desplazamiento de la diagonal.

**Ejemplo:**


In [23]:
np.eye(3)  # Matriz identidad 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])



---

### **Resumen**

| Método       | Descripción                                      |
|--------------|--------------------------------------------------|
| `np.zeros`   | Array lleno de ceros.                           |
| `np.ones`    | Array lleno de unos.                            |
| `np.arange`  | Array con valores dentro de un rango específico.|
| `np.linspace`| Valores igualmente espaciados dentro de un rango.|
| `np.random`  | Valores aleatorios (uniformes, normales, enteros).|
| `np.eye`     | Matriz identidad.                               |

---

# **Indexación de Arrays en NumPy**

NumPy permite acceder y manipular datos de arrays de manera eficiente utilizando **indexación**, **slicing** y técnicas avanzadas. Estas herramientas son fundamentales para trabajar con subconjuntos de datos o modificar estructuras existentes.

Es importante destacar que tanto la **búsqueda** como la **manipulación** de datos utilizan la indexación como su motor principal. La indexación proporciona la base para localizar elementos específicos en un array, lo que permite no solo acceder a ellos, sino también aplicar transformaciones o realizar modificaciones directamente.

---

## **1. Indexación**

Un array de NumPy es una estructura de datos indexada. La indexación es similar a la de las listas en Python, pero NumPy ofrece capacidades adicionales para arrays multidimensionales.

**Ejemplo de Indexación:**
- Acceso al primer elemento: `array[0]`
- Acceso al último elemento: `array[-1]`

In [ ]:
import numpy as np

# Crear un array de ejemplo
array = np.array([10, 20, 30, 40, 50])

# Acceso por índice
print("Primer elemento:", array[0])  # Primer elemento
print("Último elemento:", array[-1])  # Último elemento

---

## **2. Slicing (Segmentación)**

El **slicing** permite acceder a subconjuntos de un array utilizando rangos. Esto es útil para trabajar con partes específicas de los datos.

**Sintaxis básica de slicing**:
- `array[inicio:fin]`: Accede a elementos desde el índice `inicio` hasta `fin - 1`.
- `array[:fin]`: Desde el inicio hasta el índice `fin - 1`.
- `array[inicio:]`: Desde el índice `inicio` hasta el final.


In [ ]:
# Crear un array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Slicing básico
print("Elementos del índice 1 al 3:", array[1:4])  # Elementos del índice 1 al 3
print("Primeros 3 elementos:", array[:3])         # Primeros 3 elementos
print("Desde el índice 2 hasta el final:", array[2:])  # Desde el índice 2 hasta el final

---

## **3. Indexación en Arrays Multidimensionales**

Los arrays multidimensionales permiten acceder a filas, columnas o elementos específicos utilizando tuplas de índices.

**Ejemplo de Indexación Multidimensional:**
- Acceso a un elemento específico: `array2D[fila, columna]`
- Acceso a una fila completa: `array2D[fila, :]`
- Acceso a una columna completa: `array2D[:, columna]`


In [ ]:
# Crear un array 2D
array2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a elementos específicos
print("Elemento en la fila 1, columna 2:", array2D[1, 2])  # Elemento en la fila 1, columna 2

# Acceder a una fila completa
print("Primera fila:", array2D[0, :])  # Primera fila

# Acceder a una columna completa
print("Segunda columna:", array2D[:, 1])  # Segunda columna


# **Resumen de Indexación en NumPy**

La siguiente tabla resume las principales técnicas de indexación en NumPy, con una breve descripción y ejemplos para cada una.

| **Técnica**               | **Descripción**                                                                 | **Ejemplo**                                                   |
|---------------------------|-------------------------------------------------------------------------------|-------------------------------------------------------------|
| **Indexación básica**      | Accede a elementos individuales usando índices enteros.                       | `array[0]` (primer elemento)                                |
| **Indexación negativa**    | Accede a elementos contando desde el final del array.                         | `array[-1]` (último elemento)                               |
| **Slicing**                | Selecciona subconjuntos de datos mediante rangos.                             | `array[1:4]` (índices del 1 al 3)                           |
| **Indexación multidimensional** | Accede a elementos en arrays 2D o ND usando tuplas de índices.                 | `array2D[1, 2]` (fila 1, columna 2)                        |
| **Filas completas**        | Selecciona una fila completa en un array multidimensional.                    | `array2D[0, :]` (primera fila)                              |
| **Columnas completas**     | Selecciona una columna completa en un array multidimensional.                 | `array2D[:, 1]` (segunda columna)                           |
| **Indexación booleana(Mascaras)**    | Selecciona elementos que cumplan una condición lógica.                        | `array[array > 25]` (elementos mayores a 25)                |
| **Indexación condicional** | Modifica elementos que cumplan una condición.                                | `array[array > 25] = 0` (sustituye mayores a 25 por 0)      |
| **Slicing avanzado**       | Combinación de índices y slicing para seleccionar subconjuntos complejos.     | `array2D[1:, 1:]` (fila 1 en adelante y columna 1 en adelante) |
| **Iteración con `.flat`**  | Recorre los elementos del array como si fueran unidimensionales.              | `for elem in array.flat: print(elem)`                       |

---

### **Notas importantes**:
- Las técnicas de indexación en NumPy son más rápidas y eficientes que los bucles tradicionales en Python.
- La mayoría de las operaciones devuelven vistas del array original (no copias), por lo que los cambios afectan el array base.

---

# **Búsqueda de Datos en Arrays de NumPy**

La **búsqueda de datos** en NumPy es una de las aplicaciones principales de la indexación. Esta técnica permite localizar elementos de un array para su análisis o manipulación, ya sea directamente por posición o mediante condiciones lógicas.

---


## **1. Búsqueda Directa por Índices**

Esta técnica utiliza índices numéricos para localizar elementos en arrays. Los índices comienzan en `0` (como en las listas de Python) y también permiten valores negativos para acceder desde el final del array.

### **¿Para qué sirve?**
- Acceder rápidamente a elementos específicos.
- Extraer filas, columnas o submatrices en arrays multidimensionales.
- Navegar en arrays usando índices positivos o negativos.

---

### **1.1. Acceso en Arrays Unidimensionales**

Un array unidimensional es como una lista simple. Puedes acceder a sus elementos indicando la posición deseada.

**Fórmula:**
Cuando \( a \) es un array unidimensional, para acceder al elemento en la posición \( i \):
\[
a[i]
\]

**Ejemplo:**


In [ ]:
# Creación de un array unidimensional
array = np.array([10, 20, 30, 40, 50])

# Acceso al primer elemento
primer_elemento = array[0]  # Resultado: 10

# Acceso al último elemento
ultimo_elemento = array[-1]  # Resultado: 50

# Acceso a un elemento intermedio
tercer_elemento = array[2]  # Resultado: 30

# Imprimimos resultados
print("Primer elemento:", primer_elemento)
print("Último elemento:", ultimo_elemento)
print("Tercer elemento:", tercer_elemento)

### **Casos de uso en arrays unidimensionales**
1. Acceso directo a datos por posición.
2. Recuperar valores en una secuencia específica.
3. Navegar de manera rápida por elementos desde el inicio o el final del array.


### **1.2. Acceso en Arrays Multidimensionales**

En arrays multidimensionales, cada elemento se identifica mediante múltiples índices (uno para cada dimensión). Por ejemplo, en un array de dos dimensiones (matriz), necesitas especificar:
- La posición de la fila.
- La posición de la columna.

**Fórmula:**
El elemento en la posición \(i, j\) de un array bidimensional se representa como:
\[
a[i, j]
\]
Donde:
- \(i\): Índice de la fila.
- \(j\): Índice de la columna.

**Ejemplo:**


In [ ]:
# Creación de un array bidimensional (matriz)
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceso al elemento de la fila 1, columna 2
elemento = matriz[1, 2]  # Resultado: 6

# Acceso al primer elemento (fila 0, columna 0)
primer_elemento = matriz[0, 0]  # Resultado: 1

# Acceso al último elemento (última fila, última columna)
ultimo_elemento = matriz[-1, -1]  # Resultado: 9

# Imprimimos resultados
print("Elemento fila 1, columna 2:", elemento)
print("Primer elemento:", primer_elemento)
print("Último elemento:", ultimo_elemento)

### **Casos de uso en arrays multidimensionales**
1. Extraer valores específicos en tablas, matrices o imágenes.
2. Navegar entre filas y columnas.
3. Facilitar análisis de datos organizados en estructuras bidimensionales.

---


### **1.3. Uso de Indexación Negativa**

Los índices negativos permiten acceder a los elementos desde el final del array sin conocer su longitud. Esto es especialmente útil para:
- Recuperar el último elemento rápidamente.
- Acceder a los elementos más cercanos al final.

**Fórmula:**
Cuando \( a \) es un array, para acceder al último elemento:
\[
a[-1]
\]

**Ejemplo:**


In [36]:
# Usando índices negativos en un array unidimensional
ultimo = array[-1]  # Último elemento: 50
penultimo = array[-2]  # Penúltimo elemento: 40

# Usando índices negativos en un array bidimensional
ultimo_elemento_matriz = matriz[-1, -1]  # Último elemento de la matriz: 9
penultima_fila_primera_columna = matriz[-2, 0]  # Resultado: 4

# Imprimimos resultados
print("Último elemento del array:", ultimo)
print("Penúltimo elemento del array:", penultimo)
print("Último elemento de la matriz:", ultimo_elemento_matriz)
print("Penúltima fila, primera columna:", penultima_fila_primera_columna)

Último elemento del array: 50
Penúltimo elemento del array: 40
Último elemento de la matriz: 4
Penúltima fila, primera columna: 1


### **Casos de uso para índices negativos**
1. Acceso rápido a elementos finales.
2. Navegar en datasets sin preocuparte por el tamaño del array.
3. Útil para iterar desde el final hacia el inicio.

---

### **Conclusión**

La búsqueda directa por índices es una herramienta esencial para el trabajo con datos en NumPy. Sus principales beneficios incluyen:
- Acceso inmediato a cualquier posición en un array.
- Facilidad para manejar estructuras unidimensionales y multidimensionales.
- Flexibilidad mediante índices negativos.
---


# **2. Búsqueda Basada en Condiciones**

La búsqueda condicional en NumPy permite filtrar elementos de un array que cumplen con ciertos criterios lógicos. Esto genera un nuevo array que contiene solo los valores que satisfacen la condición.

### **¿Para qué sirve?**
- Extraer subconjuntos específicos de datos.
- Filtrar valores para análisis más precisos.
- Aplicar reglas personalizadas para trabajar con los datos.

---

## **Tipos de Operadores Condicionales**

Los operadores lógicos que puedes usar en las condiciones de búsqueda incluyen:

1. **Operadores de Comparación**
   - `>`: Mayor que.
   - `<`: Menor que.
   - `>=`: Mayor o igual que.
   - `<=`: Menor o igual que.
   - `==`: Igual a.
   - `!=`: Diferente de.

2. **Operadores Lógicos**
   - `&`: AND lógico (todas las condiciones deben ser verdaderas).
   - `|`: OR lógico (al menos una condición debe ser verdadera).
   - `~`: NOT lógico (invierte la condición).

3. **Funciones para Condiciones**
   - `np.isin`: Verifica si los elementos están en una lista dada.
   - `np.logical_and`: Evalúa condiciones con AND.
   - `np.logical_or`: Evalúa condiciones con OR.
   - `np.logical_not`: Evalúa la negación de una condición.

---

### **Ejemplos Detallados**

#### **2.1. Operadores de Comparación**


Filtrar valores en un array basados en comparaciones:


In [ ]:
import numpy as np

# Array de ejemplo
array = np.array([10, 20, 30, 40, 50])

# Elementos mayores a 30
mayores_30 = array[array > 30]  # Resultado: [40, 50]

# Elementos menores o iguales a 20
menores_o_iguales_20 = array[array <= 20]  # Resultado: [10, 20]

# Elementos iguales a 30
iguales_30 = array[array == 30]  # Resultado: [30]

# Imprimimos resultados
print("Mayores a 30:", mayores_30)
print("Menores o iguales a 20:", menores_o_iguales_20)
print("Iguales a 30:", iguales_30)


#### **2.2. Operadores Lógicos**

Combinar múltiples condiciones con operadores lógicos.

# Elementos mayores a 20 Y menores a 50
entre_20_y_50 = array[(array > 20) & (array < 50)]  # Resultado: [30, 40]

# Elementos menores a 20 O iguales a 50
menores_o_50 = array[(array < 20) | (array == 50)]  # Resultado: [10, 50]

# Elementos NO iguales a 30
no_30 = array[array != 30]  # Resultado: [10, 20, 40, 50]

# Imprimimos resultados
print("Entre 20 y 50:", entre_20_y_50)
print("Menores a 20 o iguales a 50:", menores_o_50)
print("Diferentes de 30:", no_30)

#### **2.3. Funciones Para Condiciones**

Utilizar funciones de NumPy para realizar búsquedas más avanzadas.

In [ ]:
# Verificar si los elementos están en una lista dada
en_lista = array[np.isin(array, [20, 40])]  # Resultado: [20, 40]

# AND lógico con np.logical_and
entre_10_y_30 = array[np.logical_and(array > 10, array < 30)]  # Resultado: [20]

# OR lógico con np.logical_or
menores_20_o_mayores_40 = array[np.logical_or(array < 20, array > 40)]  # Resultado: [10, 50]

# NOT lógico con np.logical_not
no_menores_40 = array[np.logical_not(array < 40)]  # Resultado: [40, 50]

# Imprimimos resultados
print("En lista [20, 40]:", en_lista)
print("Entre 10 y 30:", entre_10_y_30)
print("Menores a 20 o mayores a 40:", menores_20_o_mayores_40)
print("No menores a 40:", no_menores_40)


---

### **Tabla Resumen de Condiciones en NumPy**

| **Operador/Función**   | **Descripción**                             | **Ejemplo**                      |
|-------------------------|---------------------------------------------|-----------------------------------|
| `>`                    | Mayor que                                  | `array[array > 10]`              |
| `<`                    | Menor que                                  | `array[array < 50]`              |
| `>=`                   | Mayor o igual que                          | `array[array >= 20]`             |
| `<=`                   | Menor o igual que                          | `array[array <= 40]`             |
| `==`                   | Igual a                                    | `array[array == 30]`             |
| `!=`                   | Diferente de                               | `array[array != 10]`             |
| `&`                    | AND lógico (todas las condiciones)         | `(array > 20) & (array < 50)`    |
| `|`                    | OR lógico (al menos una condición)         | `(array < 20) | (array == 50)`   |
| `~`                    | NOT lógico (inversión)                     | `~(array < 40)`                  |
| `np.isin`              | Elementos en una lista                     | `np.isin(array, [10, 30])`       |
| `np.logical_and`       | Condiciones combinadas con AND             | `np.logical_and(a > 10, a < 30)` |
| `np.logical_or`        | Condiciones combinadas con OR              | `np.logical_or(a < 10, a > 40)`  |
| `np.logical_not`       | Inversión de una condición                 | `np.logical_not(a < 20)`         |

---

### **Conclusión**

La búsqueda basada en condiciones en NumPy permite filtrar y trabajar con subconjuntos específicos de datos de manera eficiente. Con una combinación de operadores de comparación, operadores lógicos y funciones avanzadas, puedes construir reglas complejas para análisis o manipulación de datos.

## **3. Métodos Avanzados para Búsqueda**

NumPy incluye métodos avanzados que permiten realizar búsquedas más precisas y complejas en arrays. Estos métodos son útiles para:
1. **Localizar índices** que cumplan con una condición.
2. **Identificar valores máximos o mínimos** y sus posiciones.
3. **Reemplazar valores** condicionalmente.

En este apartado exploraremos las siguientes funciones:
1. `np.where`
2. `np.argmax`
3. `np.argmin`

Cada una será desglosada con una breve explicación, ejemplos prácticos y casos de uso.

---

### **`np.where`**

Esta función permite encontrar los índices de los elementos que cumplen una condición o reemplazar valores basados en dicha condición.

#### **Usos principales:**
1. **Localizar índices** donde una condición es verdadera.
2. **Reemplazar valores** en función de una condición.

#### **Sintaxis de `np.where`**

`np.where(condición, valor_si_verdadero, valor_si_falso)`

- Si solo se proporciona la `condición`, devuelve los índices donde esta se cumple.
- Si se incluyen `valor_si_verdadero` y `valor_si_falso`, devuelve un array con los valores evaluados según la condición.



In [ ]:
import numpy as np

# Array de ejemplo
array = np.array([10, 20, 30, 40, 50])

# Localizar índices donde los valores son mayores a 30
indices = np.where(array > 30)  # Resultado: (array([3, 4]),)

# Reemplazar valores menores a 30 por 0
nuevo_array = np.where(array < 30, 0, array)  # Resultado: [ 0  0 30 40 50]

# Imprimimos resultados
print("Índices de valores mayores a 30:", indices)
print("Array con valores reemplazados:", nuevo_array)


### **`np.argmax`**

Esta función devuelve el **índice del valor máximo** en un array. Es útil para localizar posiciones clave en datasets grandes.

#### **Usos principales:**
1. Identificar el índice del valor máximo.
2. Analizar posiciones en arrays unidimensionales o multidimensionales (con el parámetro `axis`).

#### **Sintaxis de `np.argmax`**

`np.argmax(array, axis=None)`

- Devuelve el índice del valor máximo en el array.
- Si `axis=None` (por defecto), evalúa el array completo.
- Si se especifica un eje (`axis=0` o `axis=1`), evalúa el máximo por filas o columnas.




In [ ]:
# Índice del valor máximo en un array unidimensional
indice_maximo = np.argmax(array)  # Resultado: 4

# Array bidimensional
matriz = np.array([[10, 50, 30], [5, 60, 20]])

# Índice del valor máximo en toda la matriz
indice_maximo_matriz = np.argmax(matriz)  # Resultado: 4 (índice lineal)

# Índices de valores máximos por columna
maximos_por_columna = np.argmax(matriz, axis=0)  # Resultado: [0, 1, 0]

# Imprimimos resultados
print("Índice del valor máximo en array:", indice_maximo)
print("Índice del valor máximo en matriz:", indice_maximo_matriz)
print("Índices de máximos por columna:", maximos_por_columna)


### **`np.argmin`**

Esta función devuelve el **índice del valor mínimo** en un array. Similar a `np.argmax`, permite identificar posiciones clave en datos.

#### **Usos principales:**
1. Localizar el índice del valor mínimo.
2. Evaluar mínimos en arrays unidimensionales o multidimensionales (usando `axis`).


#### **Sintaxis de `np.argmin`**

`np.argmin(array, axis=None)`

- Devuelve el índice del valor mínimo en el array.
- Si `axis=None` (por defecto), evalúa el array completo.
- Si se especifica un eje (`axis=0` o `axis=1`), evalúa el mínimo por filas o columnas.

In [ ]:
# Índice del valor mínimo en un array unidimensional
indice_minimo = np.argmin(array)  # Resultado: 0

# Índices de valores mínimos por fila
minimos_por_fila = np.argmin(matriz, axis=1)  # Resultado: [0, 0]

# Imprimimos resultados
print("Índice del valor mínimo en array:", indice_minimo)
print("Índices de mínimos por fila:", minimos_por_fila)


### **Tabla Resumen de Métodos Avanzados**

| **Método**         | **Descripción**                                                  | **Ejemplo**                                |
|---------------------|--------------------------------------------------------------|--------------------------------------------|
| `np.where`          | Devuelve índices donde una condición es verdadera.           | `np.where(array > 20)`                     |
| `np.where`          | Reemplazar valores según una condición.                      | `np.where(array < 30, 0, array)`           |
| `np.argmax`         | Índice del valor máximo en el array.                         | `np.argmax                                 |

---

### **Conclusión**

Los métodos avanzados para búsqueda en NumPy, como `np.where`, `np.argmax` y `np.argmin`, son herramientas esenciales para localizar, analizar y transformar datos de manera eficiente. Estas funciones son particularmente útiles en análisis de datos y optimización de procesos con grandes datasets. Su flexibilidad para trabajar con condiciones y ejes permite adaptar las búsquedas a necesidades específicas.


# **Manipulación de Datos en Arrays**

NumPy permite manipular directamente los valores de un array, ya sea modificando elementos específicos, rangos de datos o aplicando operaciones sobre subconjuntos. Estas funcionalidades son útiles para preparar datos, realizar cálculos y actualizar valores de forma eficiente.

---

## **1. Modificar Elementos en un Array**

Podemos modificar el valor de un elemento específico en un array indicando su índice.

### **Sintaxis:**
`array[indice] = nuevo_valor`

---

### **Ejemplo: Modificar un Elemento**


In [ ]:
import numpy as np

# Crear un array
array = np.array([10, 20, 30, 40, 50])

# Modificar el valor del elemento en el índice 2
array[2] = 99

# Imprimir resultados
print("Array modificado:", array)  # Resultado: [10 20 99 40 50]


## **2. Modificar Rangos en un Array**

También podemos modificar múltiples elementos a la vez utilizando slicing (`inicio:fin`).

### **Sintaxis:**
`array[inicio:fin] = [nuevos_valores]`

---

### **Ejemplo: Modificar un Rango**


# Modificar un rango del array
array[1:4] = [77, 88, 99]

# Imprimir resultados
print("Array después de modificar un rango:", array)  # Resultado: [10 77 88 99 50]


## **3. Operaciones sobre Subconjuntos**

NumPy permite realizar operaciones directamente sobre subconjuntos de un array usando slicing.

### **Ejemplo: Incrementar Valores**


In [ ]:
# Incrementar en 10 los valores de un rango
array[0:3] += 10

# Imprimir resultados
print("Array después de incrementar valores:", array)  # Resultado: [20 87 98 99 50]


### **Tabla Resumen de Manipulación de Datos**

| **Operación**             | **Ejemplo**                              | **Resultado**                           |
|---------------------------|------------------------------------------|-----------------------------------------|
| Modificar un elemento      | `array[2] = 99`                         | [10, 20, 99, 40, 50]                   |
| Modificar un rango         | `array[1:4] = [77, 88, 99]`             | [10, 77, 88, 99, 50]                   |
| Incrementar valores        | `array[0:3] += 10`                      | [20, 87, 98, 99, 50]                   |
| Condicional (mayores a 50) | `array[array > 50] *= 2`                | [20, 174, 196, 198, 50]                |

---

### **Conclusión**

Las herramientas de manipulación de datos en NumPy permiten modificar arrays de forma directa y eficiente. Ya sea para ajustar elementos individuales, actualizar rangos, o realizar operaciones condicionales, estas funcionalidades son esenciales para trabajar con datos dinámicos y preparar estructuras listas para análisis o cálculos complejos.


---

## **Máscaras Booleanas**

Las máscaras booleanas son una herramienta fundamental en NumPy para trabajar con subconjuntos de datos de manera eficiente. Estas máscaras permiten realizar operaciones como **seleccionar**, **filtrar** o **modificar** elementos de un array que cumplen ciertas condiciones lógicas, lo que las convierte en una técnica avanzada de manipulación de datos.

Este enfoque es especialmente valioso cuando se trabaja con grandes conjuntos de datos. Por ejemplo:
- Si tienes un dataset con miles de registros, las máscaras booleanas te permiten identificar y operar únicamente sobre los elementos que cumplen una serie de criterios predefinidos, sin necesidad de recurrir a bucles complejos o manipulaciones individuales.

Por lo tanto esta función es una combinacion avanzada de los modulos vistos de indexación,busqueda de datos y modificación

---


#### **Crear una Máscara Booleana**

Una máscara booleana es un array compuesto por valores `True` y `False`, generado al evaluar una condición lógica sobre los elementos de un array. 

- Los valores `True` representan los elementos que cumplen la condición.
- Los valores `False` representan los que no la cumplen.

**Ejemplo**:


In [34]:
# Crear un array
import numpy as np
array = np.array([10, 20, 30, 40, 50])

# Crear una máscara para elementos mayores a 25
mascara = array > 25
print("Máscara booleana:", mascara)  # [False False  True  True  True]


Máscara booleana: [False False  True  True  True]


---

#### **Filtrar Elementos usando una Máscara**

Puedes usar una máscara booleana para seleccionar solo los elementos que cumplen una condición.


In [35]:
# Usar la máscara para filtrar elementos
elementos_filtrados = array[mascara]
print("Elementos mayores a 25:", elementos_filtrados)  # [30 40 50]


Elementos mayores a 25: [30 40 50]


---

#### **Modificar Elementos usando Máscaras**

Las máscaras también pueden utilizarse para modificar directamente los elementos que cumplen una condición.


In [ ]:
# Modificar elementos mayores a 25
array[array > 25] = 0
print("Array modificado:", array)  # [10 20  0  0  0]

---

#### **Máscaras Combinadas**

Se pueden combinar múltiples condiciones utilizando operadores lógicos como `&` (AND) y `|` (OR).

**Ejemplo**:


# Crear un array
array = np.array([10, 20, 30, 40, 50])

# Crear una máscara combinada (mayores a 20 Y menores o iguales a 40)
mascara_combinada = (array > 20) & (array <= 40)
print("Máscara combinada:", mascara_combinada)  # [False False  True  True False]

# Filtrar elementos con la máscara combinada
elementos_filtrados = array[mascara_combinada]
print("Elementos filtrados:", elementos_filtrados)  # [30 40]

---

### **Conclusión del Módulo de Máscaras Booleanas**

Las máscaras booleanas son una herramienta fundamental en NumPy que permite realizar operaciones de selección, filtrado y modificación de datos de manera eficiente. Una forma sencilla de entender su funcionalidad es compararlas con una consulta SQL, ya que ambas comparten objetivos similares:

1. **Filtrar elementos específicos**:
   - En SQL, esto se realiza con una cláusula `WHERE`, como en `SELECT * FROM tabla WHERE columna > valor`.
   - En NumPy, usamos máscaras booleanas: `array[array > valor]`.

2. **Modificar datos condicionalmente**:
   - En SQL, esto se logra con un `UPDATE`, como en `UPDATE tabla SET columna = nuevo_valor WHERE columna > valor`.
   - En NumPy, utilizamos máscaras para identificar los elementos y asignarles nuevos valores directamente: `array[array > valor] = nuevo_valor`.

Esta analogía ayuda a comprender cómo las máscaras booleanas no solo permiten trabajar con subconjuntos de datos, sino que también facilitan operaciones complejas de forma vectorizada, sin necesidad de bucles explícitos.

---

### **Ventajas de las Máscaras Booleanas en NumPy**
- **Eficiencia**: Las operaciones son vectorizadas, procesándose en paralelo y de manera optimizada.
- **Flexibilidad**: Es posible combinar múltiples condiciones con operadores lógicos (`&`, `|`) para realizar filtros más específicos.
- **Simplicidad**: Permiten trabajar con subconjuntos de datos y realizar modificaciones directamente sobre el array original.

---

### **Resumen Comparativo**

| **Función**            | **SQL**                                          | **NumPy**                        |
|-------------------------|--------------------------------------------------|----------------------------------|
| Seleccionar elementos   | `SELECT * FROM tabla WHERE columna > valor`      | `array[array > valor]`           |
| Modificar elementos     | `UPDATE tabla SET columna = nuevo_valor WHERE ...`| `array[array > valor] = nuevo_valor` |

---


# **Operaciones con Arrays en NumPy**

NumPy proporciona herramientas rápidas y eficientes para realizar operaciones matemáticas directamente sobre arrays. Estas operaciones están optimizadas y se aplican elemento a elemento, lo que las hace ideales para manejar grandes volúmenes de datos.

---

# Crear un array de ejemplo
import numpy as np
array = np.array([1, 2, 3, 4, 5])


## **1. Suma Total: `sum()`**

El método `sum()` calcula la suma de todos los elementos del array.


In [ ]:
# Calcular la suma total
suma_total = array.sum()

# Imprimir resultado
print("Suma total:", suma_total)  

## **2. Resta: `np.diff()`**

La función `np.diff()` calcula la diferencia entre elementos consecutivos de un array.


In [ ]:
# Calcular diferencias entre elementos consecutivos
diferencias = np.diff(array)

# Imprimir resultado
print("Diferencias entre elementos consecutivos:", diferencias)  # Resultado: [10, 10, 10, 10]


## **3. Suma Acumulada: `cumsum()`**

El método `cumsum()` calcula la suma acumulada de los elementos del array.


In [ ]:
# Calcular la suma acumulada
suma_acumulada = array.cumsum()

# Imprimir resultado
print("Suma acumulada:", suma_acumulada) 

## **4. Multiplicación Elemento a Elemento: `multiply()`**

El método `np.multiply()` realiza la multiplicación elemento a elemento entre dos arrays.


In [ ]:
# Crear arrays de ejemplo
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Multiplicación elemento a elemento
multiplicacion = np.multiply(array1, array2)

# Imprimir resultados
print("Multiplicación elemento a elemento:", multiplicacion)  # Resultado: [4, 10, 18]

## **5. División Elemento a Elemento: `divide()`**

El método `np.divide()` divide elemento a elemento entre dos arrays. Maneja divisiones por cero retornando `inf` o `NaN` cuando sea necesario.


In [ ]:
# División elemento a elemento
division = np.divide(array1, array2)

# Imprimir resultados
print("División elemento a elemento:", division)  # Resultado: [0.25, 0.4, 0.5]

## **6. Resto de la División: `mod()`**

El método `np.mod()` calcula el módulo (resto de la división) entre los elementos de dos arrays.


In [ ]:
# Cálculo del módulo
modulo = np.mod(array1, array2)

# Imprimir resultados
print("Módulo elemento a elemento:", modulo)  # Resultado: [1, 2, 3]

## **7. Potencia Elemento a Elemento: `power()`**

El método `np.power()` eleva cada elemento de un array a la potencia del elemento correspondiente en otro array.

In [43]:
# Potencia elemento a elemento
potencia = np.power(array1, array2)

# Imprimir resultados
print("Potencia elemento a elemento:", potencia)  # Resultado: [1, 32, 729]

Potencia elemento a elemento: [ 1 16]


## **8. Producto Punto: `dot()`**

El método `np.dot()` calcula el producto punto de dos arrays. Para matrices, equivale al producto matricial.


In [ ]:
# Producto punto
producto_punto = np.dot(array1, array2)

# Imprimir resultados
print("Producto punto:", producto_punto)  # Resultado: 32

## **Tabla Resumen**

| **Método/Función**  | **Propósito**                     | **Ejemplo**                          |
|---------------------|-----------------------------------|--------------------------------------|
| `sum()`             | Suma de todos los elementos.     | `array.sum()`                       |
| `np.diff()`          | Resta de los elementos. | `np.diff(array)`                    |
| `cumsum()`          | Suma acumulada de los elementos. | `array.cumsum()`                    |
| `np.multiply()`     | Multiplicación elemento a elemento entre dos arrays.    | `np.multiply(array1, array2)`    |
| `np.divide()`       | División elemento a elemento entre dos arrays.          | `np.divide(array1, array2)`      |
| `np.mod()`          | Cálculo del módulo entre los elementos de dos arrays.   | `np.mod(array1, array2)`         |
| `np.power()`        | Eleva elementos de un array a la potencia de otro.      | `np.power(array1, array2)`       |
| `np.dot()`          | Producto punto entre dos arrays.                       | `np.dot(array1, array2)`         |


### **Conclusión**

Estas operaciones son fundamentales en el análisis y manipulación de datos, permitiendo obtener información estadística básica y relaciones entre los datos de forma rápida y eficiente. 


## **Operaciones con Valores `NaN` en NumPy**

NumPy incluye funciones especiales diseñadas para trabajar con valores `NaN` (*Not a Number*), los cuales suelen aparecer en datasets incompletos o en operaciones matemáticas que generan resultados indefinidos, como divisiones por cero.

Las funciones `NaN-aware` son variantes de las operaciones estándar de NumPy, pero están optimizadas para ignorar los valores `NaN`. Esto permite realizar cálculos confiables sin necesidad de limpiar los datos manualmente.

---

### **Funciones Disponibles:**

1. **`np.nansum()`**
   - Calcula la suma de los elementos ignorando los valores `NaN`.
   - **Uso típico:** Cuando tienes datos incompletos y deseas sumar los valores válidos sin preocuparte por los valores faltantes.

2. **`np.nanmean()`**
   - Calcula el promedio de los elementos ignorando los valores `NaN`.
   - **Ventaja:** Proporciona un promedio representativo incluso si hay datos faltantes.

3. **`np.nanstd()`**
   - Calcula la desviación estándar ignorando los valores `NaN`.
   - **Ventaja:** Útil para evaluar la dispersión de datos con valores faltantes.

4. **`np.nanvar()`**
   - Calcula la varianza ignorando los valores `NaN`.
   - **Uso típico:** Determinar la variabilidad de datos incompletos.

5. **`np.nanmin()` y `np.nanmax()`**
   - Encuentran el mínimo y máximo ignorando los valores `NaN`.
   - **Ventaja:** Útil para encontrar extremos en datasets incompletos.

6. **`np.nanpercentile()`**
   - Calcula percentiles ignorando los valores `NaN`.
   - **Uso típico:** Análisis estadístico avanzado de datos incompletos.

---

### **¿Por qué usar estas funciones?**

1. **Eficiencia:** Estas funciones eliminan la necesidad de limpiar manualmente los datos para valores `NaN`, lo que ahorra tiempo y esfuerzo.
2. **Robustez:** Garantizan que los cálculos sean correctos incluso en presencia de datos faltantes.
3. **Compatibilidad:** Son ideales para trabajar con grandes volúmenes de datos donde los valores faltantes son inevitables.
4. **Automatización:** Permiten realizar análisis estadísticos directamente sin preocuparte por posibles errores causados por los `NaN`.

---

### **Ventajas de las Operaciones con `NaN`**

- **Evitan Errores Matemáticos:** Las operaciones estándar pueden devolver `NaN` cuando encuentran valores faltantes, lo que puede interrumpir flujos de trabajo. Estas funciones eliminan ese problema.
- **Análisis Más Confiable:** Los resultados no se ven afectados por valores faltantes, lo que proporciona una representación más precisa del dataset.
- **Mayor Flexibilidad:** Puedes enfocarte en el análisis sin tener que preocuparte por limpiar valores faltantes.

---

### **Tabla Resumen de Funciones con `NaN`**

| **Función**           | **Propósito**                                  | **Descripción**                                         |
|-----------------------|-----------------------------------------------|-------------------------------------------------------|
| `np.nansum()`         | Suma ignorando `NaN`.                        | Suma solo los valores válidos en el array.            |
| `np.nanmean()`        | Promedio ignorando `NaN`.                    | Calcula la media aritmética de los valores válidos.   |
| `np.nanstd()`         | Desviación estándar ignorando `NaN`.          | Evalúa la dispersión de los datos sin `NaN`.          |
| `np.nanvar()`         | Varianza ignorando `NaN`.                     | Calcula la variabilidad de los datos válidos.         |
| `np.nanmin()`         | Valor mínimo ignorando `NaN`.                | Encuentra el menor valor válido en el array.          |
| `np.nanmax()`         | Valor máximo ignorando `NaN`.                | Encuentra el mayor valor válido en el array.          |
| `np.nanpercentile()`  | Percentiles ignorando `NaN`.                 | Calcula percentiles mientras ignora los `NaN`.        |

---

### **Conclusión**

Las funciones con soporte para `NaN` en NumPy son herramientas esenciales para trabajar con datos incompletos. Estas funciones no solo ahorran tiempo y esfuerzo al ignorar automáticamente los valores faltantes, sino que también garantizan que los análisis sean precisos y confiables. Usarlas es una práctica recomendada cuando se manejan datasets reales, donde los datos faltantes son comunes.


# **Operaciones Adicionales con Arrays en NumPy**

NumPy incluye muchas operaciones útiles para el análisis y manipulación de datos, como encontrar máximos, mínimos, calcular desviaciones estándar, varianza y más.


In [ ]:
# Crear un array de ejemplo
import numpy as np
array = np.array([1, 2, 3, 4, 5])

## **1. Máximo: `max()`**

El método `max()` devuelve el valor máximo de los elementos del array.


In [ ]:
# Calcular el máximo
maximo = array.max()

# Imprimir resultado
print("Máximo:", maximo)  # Resultado: 5

## **2. Mínimo: `min()`**

El método `min()` devuelve el valor mínimo de los elementos del array.

In [ ]:
# Calcular el mínimo
minimo = array.min()

# Imprimir resultado
print("Mínimo:", minimo)  # Resultado: 1

## **3. Promedio: `mean()`**

El método `mean()` devuelve el promedio (media aritmética) de los elementos del array.


In [ ]:
# Calcular el promedio
promedio = array.mean()

# Imprimir resultado
print("Promedio:", promedio) 

## **4. Mediana: `median()`**

La mediana se calcula utilizando la función `np.median()`, ya que no es un método directo del objeto array.


In [ ]:
# Calcular la mediana
mediana = np.median(array)

# Imprimir resultado
print("Mediana:", mediana)  

## **5. Desviación Estándar: `std()`**

El método `std()` calcula la desviación estándar de los elementos del array, una medida de la dispersión de los datos.

In [ ]:
# Calcular la desviación estándar
desviacion_estandar = array.std()

# Imprimir resultado
print("Desviación estándar:", desviacion_estandar)  # Resultado: 1.414

## **6. Varianza: `var()`**

El método `var()` calcula la varianza de los elementos del array, que es el cuadrado de la desviación estándar.


In [ ]:
# Calcular la varianza
varianza = array.var()

# Imprimir resultado
print("Varianza:", varianza)  # Resultado: 2.0

## **7. Correlación: `np.corrcoef()`**

La correlación entre dos arrays se calcula utilizando la función `np.corrcoef()`.

In [ ]:
# Crear dos arrays de ejemplo
array1 = np.array([1, 2, 3])
array2 = np.array([10, 20, 30])

# Calcular la correlación
correlacion = np.corrcoef(array1, array2)

# Imprimir resultado
print("Correlación:\n", correlacion)

## **8. Rango de los Datos: `ptp()`**

El método `ptp()` calcula el rango (diferencia entre el valor máximo y mínimo) del array.


In [ ]:
# Calcular el rango
rango = array.ptp()

# Imprimir resultado
print("Rango:", rango)  # Resultado: 4


### **Tabla Resumen de Operaciones Matemáticas**

| **Función**           | **Propósito**                                       | **Descripción**                                                      |
|-----------------------|---------------------------------------------------|----------------------------------------------------------------------|
| `np.max()`            | Valor máximo.                                     | Devuelve el valor máximo en el array o a lo largo de un eje.        |
| `np.min()`            | Valor mínimo.                                     | Devuelve el valor mínimo en el array o a lo largo de un eje.        |
| `np.mean()`           | Promedio.                                         | Calcula la media aritmética de los valores en el array.             |
| `np.median()`         | Mediana.                                          | Encuentra el valor medio de los datos (punto central).              |
| `np.std()`            | Desviación estándar.                              | Evalúa la dispersión de los datos en el array.                      |
| `np.var()`            | Varianza.                                         | Calcula la variabilidad de los datos en el array.                   |
| `np.corrcoef()`       | Correlación.                                      | Calcula la matriz de correlación entre dos o más arrays.            |
| `np.ptp()`            | Rango (máximo - mínimo).                          | Devuelve la diferencia entre el valor máximo y mínimo del array.    |

### **Conclusión**

Estas operaciones adicionales de NumPy amplían el rango de análisis estadístico básico y avanzado que puedes realizar directamente sobre arrays, ayudándote a extraer información clave de los datos.


# **Broadcasting en NumPy**

El **broadcasting** es una funcionalidad poderosa de NumPy que permite realizar operaciones entre arrays de diferentes formas (dimensiones) sin necesidad de copiarlos o reestructurarlos explícitamente.

Cuando NumPy encuentra arrays con formas incompatibles para una operación matemática, intenta ajustarlos automáticamente siguiendo las **reglas de broadcasting**. Esto ahorra memoria y tiempo computacional al evitar la duplicación innecesaria de datos.

## **1. ¿Cómo Funciona el Broadcasting?**

NumPy aplica estas reglas para realizar broadcasting:

1. **Regla 1:** Si los arrays tienen un número diferente de dimensiones, se agrega un eje de tamaño 1 a la izquierda del array de menor dimensión.
2. **Regla 2:** Si los tamaños de los ejes no coinciden, pero uno de ellos es 1, NumPy "estira" el eje de tamaño 1 para que coincida con el tamaño del otro array.
3. **Regla 3:** Si los tamaños de los ejes no coinciden y ninguno es 1, la operación no es válida.

## **2. Ejemplos de Broadcasting**

### **2.1. Operaciones entre Escalar y Array**

Un escalar puede ser transmitido para operar sobre todos los elementos de un array.


In [ ]:
# Array unidimensional
array = np.array([1, 2, 3, 4])

# Broadcasting: escalar sumado a un array
resultado = array + 10

# Imprimir resultado
print("Array original:", array)       # [1, 2, 3, 4]
print("Resultado del broadcasting:", resultado)  # [11, 12, 13, 14]


### **2.2. Operaciones entre Arrays de Diferente Dimensión**

Un array unidimensional puede ser "estirado" para operar con un array bidimensional.


In [ ]:
# Array bidimensional
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Array unidimensional
vector = np.array([10, 20, 30])

# Broadcasting: suma entre matriz y vector
resultado = matriz + vector

# Imprimir resultados
print("Matriz original:\n", matriz)
print("Vector:\n", vector)
print("Resultado del broadcasting:\n", resultado)

### **2.3. Operaciones con Dimensiones Agregadas**

Si los tamaños no coinciden, pero una dimensión tiene tamaño 1, NumPy puede estirar ese eje para que coincidan.

#### **Ejemplo: Array Bidimensional y Array Unidimensional (eje 0)**


In [ ]:
# Array bidimensional
matriz = np.array([[1, 2, 3], [4, 5, 6]])

# Array unidimensional (columna)
vector_columna = np.array([[10], [20]])

# Broadcasting: suma entre matriz y vector_columna
resultado = matriz + vector_columna

# Imprimir resultados
print("Matriz original:\n", matriz)
print("Vector columna:\n", vector_columna)
print("Resultado del broadcasting:\n", resultado)

## **3. Casos en los que el Broadcasting Falla**

El broadcasting no funciona cuando las dimensiones de los arrays son incompatibles y no cumplen las reglas mencionadas.

#### **Ejemplo: Arrays Incompatibles**
Un array bidimensional y un array unidimensional con tamaños no compatibles generan un error.

In [ ]:
# Array bidimensional
matriz = np.array([[1, 2], [3, 4]])

# Array unidimensional con tamaño incompatible
vector_incompatible = np.array([10, 20, 30])

# Intentar una operación genera un error
try:
    resultado = matriz + vector_incompatible
except ValueError as e:
    print("Error de broadcasting:", e)

### **Conclusión**

El broadcasting en NumPy permite realizar operaciones matemáticas entre arrays de diferentes formas de manera eficiente. Comprender sus reglas y limitaciones es fundamental para aprovechar al máximo esta funcionalidad y evitar errores en el manejo de datos.
